insert into product (id, name, price_per_unit, category_id, image_url) values (1, 'That''s Entertainment', 836, 1, 'http://dummyimage.com/243x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (2, 'Ideal Husband, An', 629, 3, 'http://dummyimage.com/226x100.png/cc0000/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (3, 'Yol (a.k.a. The Way)', 484, 1, 'http://dummyimage.com/246x100.png/cc0000/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (4, 'House Arrest', 890, 1, 'http://dummyimage.com/197x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (5, 'Amityville: A New Generation', 577, 2, 'http://dummyimage.com/213x100.png/dddddd/000000');
insert into product (id, name, price_per_unit, category_id, image_url) values (6, 'Down From the Mountain', 548, 1, 'http://dummyimage.com/224x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (7, 'David Cross: Let America Laugh', 457, 1, 'http://dummyimage.com/177x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (8, 'God''s Gun', 684, 3, 'http://dummyimage.com/235x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (9, 'Little Miss Marker', 800, 2, 'http://dummyimage.com/153x100.png/cc0000/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (10, 'Tap', 206, 1, 'http://dummyimage.com/183x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (11, 'For a Few Dollars More (Per qualche dollaro in più)', 127, 3, 'http://dummyimage.com/150x100.png/cc0000/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (12, 'Muck', 876, 3, 'http://dummyimage.com/139x100.png/cc0000/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (13, 'Encore', 135, 2, 'http://dummyimage.com/187x100.png/cc0000/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (14, 'Love Is All You Need (Den skaldede frisør)', 886, 1, 'http://dummyimage.com/247x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (15, 'Urban Ghost Story', 625, 1, 'http://dummyimage.com/106x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (16, 'Beyond All Boundaries', 211, 3, 'http://dummyimage.com/118x100.png/cc0000/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (17, 'Aragami', 977, 2, 'http://dummyimage.com/158x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (18, 'Three Days of the Condor (3 Days of the Condor)', 660, 1, 'http://dummyimage.com/112x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (19, 'Flashback', 668, 2, 'http://dummyimage.com/139x100.png/cc0000/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (20, 'My Bodyguard', 391, 3, 'http://dummyimage.com/179x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (21, 'Rogue Cop', 693, 3, 'http://dummyimage.com/152x100.png/dddddd/000000');
insert into product (id, name, price_per_unit, category_id, image_url) values (22, 'Charlie Chan in Paris', 601, 2, 'http://dummyimage.com/121x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (23, 'Scientist, The', 327, 3, 'http://dummyimage.com/118x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (24, 'Diggers', 673, 2, 'http://dummyimage.com/151x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (25, 'Jaws', 383, 2, 'http://dummyimage.com/160x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (26, 'Song to Remember, A', 944, 2, 'http://dummyimage.com/109x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (27, 'Ganes', 993, 1, 'http://dummyimage.com/248x100.png/dddddd/000000');
insert into product (id, name, price_per_unit, category_id, image_url) values (28, 'Confess', 273, 1, 'http://dummyimage.com/244x100.png/dddddd/000000');
insert into product (id, name, price_per_unit, category_id, image_url) values (29, 'Trouble with Dee Dee, The', 568, 2, 'http://dummyimage.com/203x100.png/cc0000/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (30, 'Itinerary of a Spoiled Child', 801, 1, 'http://dummyimage.com/155x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (31, 'Hachiko: A Dog''s Story (a.k.a. Hachi: A Dog''s Tale)', 828, 1, 'http://dummyimage.com/232x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (32, 'Patton Oswalt: My Weakness Is Strong', 282, 3, 'http://dummyimage.com/234x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (33, 'Think Like a Man Too', 291, 2, 'http://dummyimage.com/122x100.png/dddddd/000000');
insert into product (id, name, price_per_unit, category_id, image_url) values (34, 'Fear Strikes Out', 111, 3, 'http://dummyimage.com/238x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (35, 'Comanche Moon', 337, 2, 'http://dummyimage.com/117x100.png/cc0000/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (36, 'I Am', 521, 2, 'http://dummyimage.com/172x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (37, 'New Best Friend', 384, 2, 'http://dummyimage.com/192x100.png/cc0000/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (38, 'Affairs of Anatol, The', 889, 1, 'http://dummyimage.com/175x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (39, 'San Pietro', 143, 2, 'http://dummyimage.com/209x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (40, 'Calling Dr. Death', 978, 1, 'http://dummyimage.com/125x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (41, 'Madeline', 808, 1, 'http://dummyimage.com/200x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (42, 'Thirteen, The (Trinadtsat)', 768, 2, 'http://dummyimage.com/175x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (43, 'Crying Game, The', 814, 1, 'http://dummyimage.com/159x100.png/dddddd/000000');
insert into product (id, name, price_per_unit, category_id, image_url) values (44, 'Filth', 866, 1, 'http://dummyimage.com/108x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (45, 'One Tough Cop', 431, 1, 'http://dummyimage.com/235x100.png/dddddd/000000');
insert into product (id, name, price_per_unit, category_id, image_url) values (46, 'Other Sister, The', 947, 3, 'http://dummyimage.com/226x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (47, 'Bad Johnson', 796, 3, 'http://dummyimage.com/134x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (48, 'Cran d''arrêt', 203, 3, 'http://dummyimage.com/223x100.png/5fa2dd/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (49, 'Hound of the Baskervilles, The', 419, 3, 'http://dummyimage.com/166x100.png/ff4444/ffffff');
insert into product (id, name, price_per_unit, category_id, image_url) values (50, 'Vuonna 85', 519, 2, 'http://dummyimage.com/193x100.png/5fa2dd/ffffff');
